name: flutter_todo
description: A TODO app. riverpod + navigator2 + switch env
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2+1
  hooks_riverpod: ^2.0.0-dev.9
  freezed_annotation: ^2.0.3
  json_annotation: ^4.4.0
  go_router: ^4.1.0
  firebase_core: ^1.14.1
  firebase_auth: ^3.3.14
  cloud_firestore: ^3.1.12
  # TODO(torikatsu): configure podfile to speed up for building ios
  # cloud_firestore: ^3.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^2.0.3+1
  build_runner: ^2.1.7
  source_gen: ^1.2.1
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
