name: flutter_todo
description: A TODO app. riverpod + navigator2 + switch env
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.0.0-dev.0
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^1.1.1
  build_runner: ^2.1.7
  source_gen: ^1.2.1
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
